### ISSUE TITLE
audioop missing

### ISSUE THREAD

**Issue by lucas42** [youknowone/python-deadlib#6]
This repository doesn't include code for `audioop`, despite it being in the [PEP 594 list](https://peps.python.org/pep-0594/#audioop).  
Is this because [audioop-lts](https://pypi.org/project/audioop-lts/) exists as an alternative?
It'd be useful to have an explanation somewhere in this repository, especially because 2 of the libraries here depend on audioop (See #5 )

**Comment by youknowone** [comment]
I decided to start by including only pure Python libraries. It might not be explicit enough, but I tried to convey the following information:

> If your project depends on a module that has been removed from the standard library, here is the redistribution of the deprecated modules in pure Python.

This is not a strict policy, but mainly due to my lack of enthusiasm for spending effort. audioop-lts didn't affect the decision because I included nntplib even though there was already an alternative library. Any patch about missing libraries will be welcome. (probably I'd better to write this in README)
For this case, if audioop-lts already exists and as long as it is compatible with legacy audioop, adding it as a dependency and updating aifc and sunau to using it will be good too.

----

This is not about the issue, but you seem to know better about python legacy libraries. Please feel free to ask maintenance permissions if are interested in.

**Comment by lucas42** [comment]
Thanks for the clarification!  I hadn't realised the distinction between pure python packages and other types.
(Though I'd never dived into the python codebase itself, until I was hit by this PEP 594 change in the release of 3.13)
